# Generated by Django 4.1.4 on 2023-03-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_services_service'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specialists',
            new_name='Specialist',
        ),
    ]
