# Generated by Django 4.1.4 on 2023-04-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='diploma',
        ),
        migrations.AddField(
            model_name='specialist',
            name='diploma_issuer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='specialist',
            name='diploma_recipient',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
