# Generated by Django 4.1.4 on 2023-03-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_specialists_specialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y-%m-%d'),
        ),
    ]
