# Generated by Django 4.1.4 on 2023-04-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='phone',
            field=models.CharField(blank=True, max_length=17, unique=True),
        ),
    ]
