# Generated by Django 4.1.4 on 2023-03-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_specialist_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='about_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialist',
            name='about_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialist',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='first_name_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='last_name_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
    ]
