# Generated by Django 4.1.4 on 2023-03-30 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_specialist_about_en_specialist_about_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialist',
            old_name='experience',
            new_name='beginning_of_the_experience',
        ),
    ]
