# Generated by Django 4.1.4 on 2023-04-03 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_specialist_beginning_of_the_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='beginning_of_the_experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1923), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
