# Generated by Django 4.1.4 on 2023-04-10 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='specialists_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.specialist'),
        ),
        migrations.AlterField(
            model_name='service',
            name='specialists_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='users.specialist'),
        ),
    ]
