# Generated by Django 4.1.4 on 2023-04-10 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_address_specialists_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='specialists_id',
            new_name='specialist',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='specialists_id',
            new_name='specialist',
        ),
    ]
