# Generated by Django 4.1.4 on 2023-03-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_city_latitude_alter_city_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='loc_latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='address',
            name='loc_longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_service',
            field=models.CharField(default='Visit a specialist', max_length=80),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_service_en',
            field=models.CharField(default='Visit a specialist', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_service_ru',
            field=models.CharField(default='Visit a specialist', max_length=80, null=True),
        ),
    ]
