# Generated by Django 4.1.4 on 2023-03-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_address_loc_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name_service',
            field=models.CharField(default="Specialist's appointment", max_length=80),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_service_en',
            field=models.CharField(default="Specialist's appointment", max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_service_ru',
            field=models.CharField(default="Specialist's appointment", max_length=80, null=True),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
