# Generated by Django 4.1.4 on 2023-03-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_address_loc_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('name_ru', models.CharField(max_length=50, null=True)),
                ('fields', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='name_service',
            field=models.CharField(default="Specialist's appointment", max_length=80),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_service_en',
            field=models.CharField(default="Specialist's appointment", max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_service_ru',
            field=models.CharField(default="Specialist's appointment", max_length=80, null=True),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
