# Generated by Django 4.1.4 on 2023-03-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_staticcontent_alter_service_name_service_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staticcontent',
            old_name='fields',
            new_name='fields_en',
        ),
        migrations.RemoveField(
            model_name='staticcontent',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='staticcontent',
            name='name_ru',
        ),
        migrations.AddField(
            model_name='staticcontent',
            name='fields_ru',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
