# Generated by Django 4.1.4 on 2023-03-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_fields_staticcontent_fields_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticcontent',
            name='name',
            field=models.SlugField(),
        ),
    ]
