# Generated by Django 4.1.4 on 2023-08-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_aboutcranio_remove_news_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-date',), 'verbose_name': 'New', 'verbose_name_plural': 'News'},
        ),
    ]
