# Generated by Django 4.1.4 on 2023-08-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_news_options_alter_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcranio',
            name='title',
            field=models.CharField(default='Super title', max_length=250, verbose_name='About title'),
            preserve_default=False,
        ),
    ]
