# Generated by Django 4.1.4 on 2023-08-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcranio',
            name='title',
            field=models.CharField(default='About Cranio', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutcranio',
            name='title_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='aboutcranio',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
