# Generated by Django 4.1.4 on 2023-06-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SPECIALIST', 'Specialist'), ('CUSTOMER', 'Customer'), ('ADMIN', 'Admin')], default='SPECIALIST', max_length=50, verbose_name='user role'),
        ),
        migrations.DeleteModel(
            name='Specialist',
        ),
    ]
