# Generated by Django 4.1.4 on 2023-06-23 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_joined_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='joined_date',
        ),
    ]
