# Generated by Django 4.1.4 on 2023-08-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Middle name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='middle_name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='middle_name_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/%Y-%m-%d', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SPECIALIST', 'Specialist'), ('CUSTOMER', 'Customer'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=50, verbose_name='user role'),
        ),
    ]
