# Generated by Django 4.1.4 on 2023-06-13 09:00

import apps.specialists.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_customuser_options_alter_customuser_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.customuser',),
        ),
        migrations.CreateModel(
            name='SpecialistData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('first_name_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='first name')),
                ('first_name_ru', models.CharField(blank=True, max_length=150, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('last_name_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='last name')),
                ('last_name_ru', models.CharField(blank=True, max_length=150, null=True, verbose_name='last name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/%Y-%m-%d', verbose_name='specialist photo')),
                ('about', models.TextField(blank=True, verbose_name='about specialist')),
                ('about_en', models.TextField(blank=True, null=True, verbose_name='about specialist')),
                ('about_ru', models.TextField(blank=True, null=True, verbose_name='about specialist')),
                ('phone', models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='phone number')),
                ('beginning_of_the_experience', models.PositiveSmallIntegerField(blank=True, null=True, validators=[apps.specialists.validators.validate_year], verbose_name='year of practice start')),
                ('diploma_issuer', models.CharField(blank=True, max_length=255, verbose_name='organization-issuer of diploma')),
                ('diploma_recipient', models.CharField(blank=True, max_length=100, verbose_name='name of diploma recipient mentioned in diploma')),
                ('status', models.CharField(choices=[('FILLING', 'application should be filled in'), ('CHECKING', 'pending diploma confirmation'), ('CORRECTING', 'application should be amended'), ('PAYMENT', 'pending payment'), ('ACTIVE', 'active therapist')], default='FILLING', max_length=50, verbose_name='status of specialist')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Specialist',
                'verbose_name_plural': 'Specialists',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service', models.CharField(max_length=100)),
                ('name_service_en', models.CharField(max_length=100, null=True)),
                ('name_service_ru', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('price', models.PositiveIntegerField()),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB')], default='USD', max_length=5)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='specialists.specialist')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_latitude', models.FloatField(verbose_name='Address latitude')),
                ('loc_longitude', models.FloatField(verbose_name='Address longitude')),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='specialists.specialist')),
            ],
        ),
    ]
