# Generated by Django 4.1.4 on 2023-06-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialistprofile',
            name='approver_comments',
            field=models.TextField(blank=True, verbose_name='Admin comments for corrections'),
        ),
        migrations.AlterField(
            model_name='specialistprofile',
            name='status',
            field=models.CharField(choices=[('FILLING', 'Application should be filled in'), ('CHECKING', 'Pending diploma confirmation'), ('CORRECTING', 'Corections are required'), ('PAYMENT', 'Pending payment'), ('ACTIVE', 'Active therapist')], default='FILLING', max_length=50, verbose_name='Status of specialist'),
        ),
    ]
