# Generated by Django 4.1.4 on 2023-08-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craniodiploma',
            name='scan',
        ),
        migrations.AddField(
            model_name='craniodiploma',
            name='file',
            field=models.FileField(default='', upload_to='diplomas/%Y-%m-%d', verbose_name='Scanned diploma'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='diplomas/%Y-%m-%d', verbose_name='Scanned document'),
        ),
    ]
