# Generated by Django 4.1.4 on 2023-06-17 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Currency slug')),
                ('name', models.CharField(max_length=20, verbose_name='Currency name')),
                ('name_en', models.CharField(max_length=20, null=True, verbose_name='Currency name')),
                ('name_ru', models.CharField(max_length=20, null=True, verbose_name='Currency name')),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='specialists.currency'),
        ),
    ]
