# Generated by Django 4.1.4 on 2023-06-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialistdata',
            old_name='beginning_of_the_experience',
            new_name='practice_start',
        ),
    ]
