# Generated by Django 4.1.4 on 2023-06-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0002_specialistprofile_approver_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialistprofile',
            name='status',
            field=models.CharField(choices=[('FILLING', 'Application should be filled in'), ('CHECKING', 'Pending diploma confirmation'), ('CORRECTING', 'Corrections are required'), ('PAYMENT', 'Pending payment'), ('ACTIVE', 'Active therapist')], default='FILLING', max_length=50, verbose_name='Status of specialist'),
        ),
    ]
