# Generated by Django 4.1.4 on 2023-08-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0002_remove_craniodiploma_scan_craniodiploma_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='languages',
            field=models.ManyToManyField(blank=True, to='specialists.language'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='service_types',
            field=models.ManyToManyField(blank=True, to='specialists.servicetype'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='speciality',
            field=models.CharField(blank=True, max_length=100, verbose_name='Speciality'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='speciality_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Speciality'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='speciality_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Speciality'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='specializations',
            field=models.ManyToManyField(blank=True, to='specialists.specialization'),
        ),
        migrations.AlterField(
            model_name='status',
            name='comments',
            field=models.CharField(blank=True, max_length=200, verbose_name='Admin comments for corrections'),
        ),
    ]
