# Generated by Django 4.1.4 on 2023-06-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0003_alter_specialistprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialistprofile',
            name='status',
            field=models.CharField(choices=[('FILLING', 'Filling the application.'), ('CHECKING', 'Pending diploma confirmation.'), ('CORRECTING', 'Corrections are required.'), ('PAYMENT', 'Pending payment.'), ('ACTIVE', 'Active therapist.')], default='FILLING', max_length=50, verbose_name='Status of specialist'),
        ),
    ]
