# Generated by Django 4.1.4 on 2023-08-17 07:13

import apps.specialists.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0004_alter_specialistprofile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CranioDiploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diploma_recipient', models.CharField(max_length=100, verbose_name='Name of diploma recipient mentioned in diploma')),
                ('diploma_year', models.SmallIntegerField(validators=[apps.specialists.validators.validate_year], verbose_name='Year of diploma issue')),
            ],
            options={
                'verbose_name': 'Education data',
                'verbose_name_plural': 'Education datas',
            },
        ),
        migrations.CreateModel(
            name='CranioInstitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='diplomas/%Y-%m-%d', verbose_name='Scanned document')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='specialists.specialist')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Specialization',
                'verbose_name_plural': 'Specializations',
            },
        ),
        migrations.CreateModel(
            name='SpecLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialists.language')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialists.specialist')),
            ],
            options={
                'verbose_name': "Specialist's Language",
                'verbose_name_plural': "Specialist's Languages",
                'default_related_name': 'spec_lang',
            },
        ),
        migrations.CreateModel(
            name='SpecSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialists.specialist')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialists.specialization')),
            ],
            options={
                'verbose_name': "Specialist's Language",
                'verbose_name_plural': "Specialist's Languages",
                'default_related_name': 'spec_spec',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('FILLING', 'Filling out the application.'), ('CHECK', 'Pending diploma confirmation.'), ('EDIT', 'Corrections are required.'), ('PAYING', 'Pending payment.'), ('ACTIVE', 'Active account.')], default='FILLING', max_length=50, verbose_name='Status of specialist')),
                ('comments', models.TextField(blank=True, verbose_name='Admin comments for corrections')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Last status update')),
                ('specialist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='specialists.specialist')),
            ],
            options={
                'verbose_name': 'Specialist Status',
                'verbose_name_plural': 'Specialists Statuses',
            },
        ),
        migrations.RemoveField(
            model_name='specialistprofile',
            name='approver_comments',
        ),
        migrations.RemoveField(
            model_name='specialistprofile',
            name='diploma_issuer',
        ),
        migrations.RemoveField(
            model_name='specialistprofile',
            name='diploma_recipient',
        ),
        migrations.RemoveField(
            model_name='specialistprofile',
            name='practice_start',
        ),
        migrations.RemoveField(
            model_name='specialistprofile',
            name='status',
        ),
        migrations.AddField(
            model_name='address',
            name='currency',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to='specialists.currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='address',
            name='min_price',
            field=models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(1, 'Value should be larger than 0.')], verbose_name='Minimal price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialistprofile',
            name='speciality',
            field=models.CharField(default='Therapist', max_length=100, verbose_name='Speciality'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specialistprofile',
            name='about',
            field=models.TextField(blank=True, max_length=2000, verbose_name='About specialist'),
        ),
        migrations.AlterField(
            model_name='specialistprofile',
            name='about_en',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='About specialist'),
        ),
        migrations.AlterField(
            model_name='specialistprofile',
            name='about_ru',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='About specialist'),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='specialization',
            name='specialist',
            field=models.ManyToManyField(related_name='specializations', through='specialists.SpecSpecialization', to='specialists.specialist'),
        ),
        migrations.AddField(
            model_name='language',
            name='specialist',
            field=models.ManyToManyField(related_name='languages', through='specialists.SpecLanguage', to='specialists.specialist'),
        ),
        migrations.AddField(
            model_name='craniodiploma',
            name='diploma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='specialists.document'),
        ),
        migrations.AddField(
            model_name='craniodiploma',
            name='diploma_issuer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='specialists.cranioinstitute'),
        ),
        migrations.AddField(
            model_name='craniodiploma',
            name='specialist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diploma', to='specialists.specialist'),
        ),
    ]
