name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_push_container:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Github Packages Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: ghcr.io/cranio-worldwide/backend:latest
  deploy:
    name: Run update backend container
    uses: Cranio-worldwide/deploy/.github/workflows/main.yml@main
    with:
      project: backend
    secrets: inherit